alias add_theme='grep -n "ZSH_THEME_RANDOM_CANDIDATES" ~/.zshrc | cut -d: -f1 | xargs -I {} sh -c "sed -i.bak '\''{}s/)/ \"$RANDOM_THEME\" )/'\'' ~/.zshrc"'
alias aliases='nano ~/.oh-my-zsh/custom/aliases.zsh'
alias cls='clear && ls'
alias CLS='clear && ls'
alias prp='poetry run pytest'
alias yoink='git pull'
alias yeet='git push'
alias hmm='git fetch'
